system:
  name: "SOCIA"
  version: "0.1.0"
  description: "Simulation Orchestration for City Intelligence and Agents"

llm:
  provider: "openai"  # options: openai, anthropic, llama, etc.
  model: "gpt-4o"
  api_key: ""  # set via environment variable OPENAI_API_KEY
  temperature: 0.7
  max_tokens: 4000
  timeout: 60  # seconds

agents:
  task_understanding:
    enabled: true
    prompt_template: "templates/task_understanding_prompt.txt"
    output_format: "json"
  
  data_analysis:
    enabled: true
    prompt_template: "templates/data_analysis_prompt.txt"
    output_format: "json"
    supported_data_types: ["csv", "json", "geojson", "shapefile"]
  
  model_planning:
    enabled: true
    prompt_template: "templates/model_planning_prompt.txt"
    output_format: "json"
    available_models: ["gravity", "agent_based", "sir", "network", "system_dynamics"]
  
  code_generation:
    enabled: true
    prompt_template: "templates/code_generation_prompt.txt"
    output_format: "python"
    code_style: "pep8"
    
  code_verification:
    enabled: true
    prompt_template: "templates/code_verification_prompt.txt"
    output_format: "json"
    run_tests: true
    
  simulation_execution:
    enabled: true
    prompt_template: "templates/simulation_execution_prompt.txt"
    output_format: "json"
    sandbox: "local"  # options: local, docker, cloud
    timeout: 300  # seconds
    
  result_evaluation:
    enabled: true
    prompt_template: "templates/result_evaluation_prompt.txt"
    output_format: "json"
    metrics: ["mse", "mae", "correlation", "distribution_kl", "dard"]
    
  feedback_generation:
    enabled: true
    prompt_template: "templates/feedback_generation_prompt.txt"
    output_format: "json"
    
  iteration_control:
    enabled: true
    prompt_template: "templates/iteration_control_prompt.txt"
    output_format: "json"
    convergence_threshold: 0.05
    
workflow:
  max_iterations: 3
  parallel_execution: false
  save_intermediate_results: true
  
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "socia.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
output:
  save_format: ["python", "json", "visualization"]
  visualization_types: ["agent_trajectories", "heatmaps", "network_graphs", "timeseries"] 